### PR TITLE
DirectedGraph.h: remove unnecessary parameter to copy constructor

### PR DESCRIPTION
**Pull request by Smattr**
@jowong4 I hope you don't mind me jumping in on this but I was in the neighborhood and stumbled across #321 myself. Apologies if you had already started addressing this. @lmjakt, can you confirm this resolves your issue?

From the truncated error message on #320, I'm guessing that has the same root cause and is also fixed by this. @sunnykevin19, does this solve your issue?

### CODE REVIEW

**Comment by lmjakt** [comment]
Hi Matthew (@Smattr),
the fix resolves my issue. Thanks for the update.

cheers,

Martin

**Comment by sjackman** [comment]
@jowong4 You may want to consider migrating from CircleCI and Azure to GitHub Actions.

**Comment by sjackman** [comment]
Thank you for your first contribution to ABySS, Matthew! 🥇

**Comment by jowong4** [comment]
@lcoombe Remind me, what was the problem with github actions and our plans currently with regards to @sjackman 's comment.

**Comment by lcoombe** [comment]
> @lcoombe Remind me, what was the problem with github actions and our plans currently with regards to @sjackman 's comment.

@jowong4 - To my knowledge there wasn't any issue with github actions -- it just wasn't a priority for us to do the migration.

**Pull request merged**
