### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by mmokrejs**
Improve README.md

### CODE REVIEW

**Comment by sjackman** [comment]
Thanks, Martin!

**Comment by mmokrejs** [comment]
Hmm, the CI logs show that the generated configure is broken:

`./configure: line 5321: : command not found`

**Comment by sjackman** [comment]
Can you please line 5321 of `./configure`?
```sh
sed -n 5321p ./configure
```

**Comment by mmokrejs** [comment]
I assume you can get to the files, see https://travis-ci.org/bcgsc/abyss/jobs/336747008

**Comment by sjackman** [comment]
Ah, I didn't realize that you were referring to the CI job.

```
./configure: line 5321: : command not found
```
https://travis-ci.org/bcgsc/abyss/jobs/336747008#L570

```
# FAIL:  12
```
https://travis-ci.org/bcgsc/abyss/jobs/336747008#L1515

I believe Ben is looking into this CI failure.

**Comment by mmokrejs** [comment]
BTW, it would be nice to further improve the README stating what openmpi/mpich/mpich2/lammpi versions are at least known to work, if you do not know minimum version requirements.

**Comment by sjackman** [comment]
We've used every nearly every version of OpenMPI release in the last ten years. We've never used nor tested other MPI implementations. I know some users have used them.
The Bloom filter de Bruijn graph assembler released with ABySS 2.0 does not require OpenMPI. You want to try it out as well. It uses one tenth of the memory of the MPI de Bruijn graph assembler.

**Comment by benvvalk** [comment]
> I believe Ben is looking into this CI failure.
Yeah, I really need to get that fixed.

@mmokrejs Thanks for the documentation fix! (merged)

**Pull request merged**
