### PR TITLE
CircleCI: Use clang 5.0 on Ubuntu 18.04 LTS (Bionic Beaver)

### PR DESCRIPTION
**Pull request by sjackman**
This PR runs `make check` with both Clang and GCC.

### CODE REVIEW

**Comment by sjackman** [comment]
@benvvalk There's no `make test` failures with clang 5.0.

**Comment by sjackman** [comment]
@benvvalk Shall I merge this PR?

**Comment by benvvalk** [comment]
Still working on this

**Comment by benvvalk** [comment]
@sjackman not yet please, I am still debugging with the current CircleCI configuration

**Comment by benvvalk** [comment]
Lots of good fix-y goodness in this PR -- sorry for letting it go stale.

I don't mind upgrading the clang testing environment now, since I've completely forgotten what I was doing in my last attempt.

**Comment by sjackman** [comment]
Thanks for merging, Ben. I think you were trying to reproduce a `make test` failure with a particular version of Clang on Linux. That's all I remember.

**Pull request merged**
