### PR TITLE
Fix BUGs of abyss-tofastq 

### PR DESCRIPTION
**Pull request by jiguanglizipao**
Fix BUG:abyss-tofastq cannot convert .fa to .fastq (EX. Use Dida)
Fix BUG:make --cat become default rather than -i (help info said --cat should be defult)

### CODE REVIEW

**Comment by sjackman** [comment]
> Fix BUG:make --cat become default rather than -i (help info said --cat should be defult)

I believe `--cat` is the default. Please provide a test case if you're not seeing this behaviour.

**Comment by sjackman** [comment]
> Fix BUG:abyss-tofastq cannot convert .fa to .fastq (EX. Use Dida)

It's by design the ABySS refuses to convert a FASTA to FASTQ and make up fake quality values. Whether it's good design or bad design can be debated.

If Dida can't read FASTA files, I'd suggest opening up a feature request issue asking @mohamadi to implement that feature. https://github.com/bcgsc/dida/issues/new

**Comment by jiguanglizipao** [comment]
Sorry, cat is default after test again.
I think we can add a new parameter to this part. Do you think it is a new feature? This bug doesn't only happen in Dida, but also in every aligner using this part(need fastq). So although this patch may not be well designed, I still submit this pull request because this bug is critical.

**Comment by jiguanglizipao** [comment]
If you think a  new parameter like "--force" is ok, I  will do that soon.

**Comment by sjackman** [comment]
Do you know of other aligners other than DIDA that will only accept FASTQ. I'd rather fix this issue in DIDA. I work with the developer of DIDA, so I'll chat with him tomorrow.

**Pull request closed without merging**
